// Code generated by MockGen. DO NOT EDIT.
// Source: service/wallet.go

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/pranayhere/simple-wallet/dto"
)

// MockWalletSvc is a mock of WalletSvc interface.
type MockWalletSvc struct {
	ctrl     *gomock.Controller
	recorder *MockWalletSvcMockRecorder
}

// MockWalletSvcMockRecorder is the mock recorder for MockWalletSvc.
type MockWalletSvcMockRecorder struct {
	mock *MockWalletSvc
}

// NewMockWalletSvc creates a new mock instance.
func NewMockWalletSvc(ctrl *gomock.Controller) *MockWalletSvc {
	mock := &MockWalletSvc{ctrl: ctrl}
	mock.recorder = &MockWalletSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletSvc) EXPECT() *MockWalletSvcMockRecorder {
	return m.recorder
}

// Deposit mocks base method.
func (m *MockWalletSvc) Deposit(ctx context.Context, depositDto dto.DepositDto) (dto.WalletTransferResultDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", ctx, depositDto)
	ret0, _ := ret[0].(dto.WalletTransferResultDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deposit indicates an expected call of Deposit.
func (mr *MockWalletSvcMockRecorder) Deposit(ctx, depositDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockWalletSvc)(nil).Deposit), ctx, depositDto)
}

// GetWalletByAddress mocks base method.
func (m *MockWalletSvc) GetWalletByAddress(ctx context.Context, walletAddress string) (dto.WalletDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByAddress", ctx, walletAddress)
	ret0, _ := ret[0].(dto.WalletDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByAddress indicates an expected call of GetWalletByAddress.
func (mr *MockWalletSvcMockRecorder) GetWalletByAddress(ctx, walletAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByAddress", reflect.TypeOf((*MockWalletSvc)(nil).GetWalletByAddress), ctx, walletAddress)
}

// GetWalletById mocks base method.
func (m *MockWalletSvc) GetWalletById(ctx context.Context, id int64) (dto.WalletDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletById", ctx, id)
	ret0, _ := ret[0].(dto.WalletDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletById indicates an expected call of GetWalletById.
func (mr *MockWalletSvcMockRecorder) GetWalletById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletById", reflect.TypeOf((*MockWalletSvc)(nil).GetWalletById), ctx, id)
}

// SendMoney mocks base method.
func (m *MockWalletSvc) SendMoney(ctx context.Context, sendMoneyDto dto.SendMoneyDto) (dto.WalletTransferResultDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMoney", ctx, sendMoneyDto)
	ret0, _ := ret[0].(dto.WalletTransferResultDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMoney indicates an expected call of SendMoney.
func (mr *MockWalletSvcMockRecorder) SendMoney(ctx, sendMoneyDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMoney", reflect.TypeOf((*MockWalletSvc)(nil).SendMoney), ctx, sendMoneyDto)
}

// Withdraw mocks base method.
func (m *MockWalletSvc) Withdraw(ctx context.Context, withdrawDto dto.WithdrawDto) (dto.WalletTransferResultDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, withdrawDto)
	ret0, _ := ret[0].(dto.WalletTransferResultDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockWalletSvcMockRecorder) Withdraw(ctx, withdrawDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockWalletSvc)(nil).Withdraw), ctx, withdrawDto)
}
