// Code generated by MockGen. DO NOT EDIT.
// Source: service/wallet.go

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/pranayhere/simple-wallet/dto"
)

// MockWalletSvc is a mock of WalletSvc interface.
type MockWalletSvc struct {
	ctrl     *gomock.Controller
	recorder *MockWalletSvcMockRecorder
}

// MockWalletSvcMockRecorder is the mock recorder for MockWalletSvc.
type MockWalletSvcMockRecorder struct {
	mock *MockWalletSvc
}

// NewMockWalletSvc creates a new mock instance.
func NewMockWalletSvc(ctrl *gomock.Controller) *MockWalletSvc {
	mock := &MockWalletSvc{ctrl: ctrl}
	mock.recorder = &MockWalletSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletSvc) EXPECT() *MockWalletSvcMockRecorder {
	return m.recorder
}

// GetWalletById mocks base method.
func (m *MockWalletSvc) GetWalletById(ctx context.Context, id int64) (dto.WalletDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletById", ctx, id)
	ret0, _ := ret[0].(dto.WalletDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletById indicates an expected call of GetWalletById.
func (mr *MockWalletSvcMockRecorder) GetWalletById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletById", reflect.TypeOf((*MockWalletSvc)(nil).GetWalletById), ctx, id)
}

// SendMoney mocks base method.
func (m *MockWalletSvc) SendMoney(ctx context.Context, sendMoneyDto dto.TransferMoneyDto) (dto.WalletTransferResultDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMoney", ctx, sendMoneyDto)
	ret0, _ := ret[0].(dto.WalletTransferResultDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMoney indicates an expected call of SendMoney.
func (mr *MockWalletSvcMockRecorder) SendMoney(ctx, sendMoneyDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMoney", reflect.TypeOf((*MockWalletSvc)(nil).SendMoney), ctx, sendMoneyDto)
}
