// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error)
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	GetBankAccount(ctx context.Context, id int64) (BankAccount, error)
	GetCurrency(ctx context.Context, code string) (Currency, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	GetWalletByAddress(ctx context.Context, address string) (Wallet, error)
	GetWalletByAddressForUpdate(ctx context.Context, address string) (Wallet, error)
	GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error)
	ListBankAccounts(ctx context.Context, arg ListBankAccountsParams) ([]BankAccount, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	ListWallets(ctx context.Context, arg ListWalletsParams) ([]Wallet, error)
	UpdateBankAccountStatus(ctx context.Context, arg UpdateBankAccountStatusParams) (BankAccount, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
